### ISSUE TITLE
下载地址 403

### ISSUE THREAD

**Issue by changdaye** [xiyouMc/WebHubBot#17]
爬下来的下载地址，如果直接在浏览器中下载 是提示 服务器拒绝的  403 错误， 
感觉需要模拟用户登录 session 或者cookie token才行。

**Comment by xiyouMc** [comment]
资源是挂在cdn的。所以有时效，应该半个小时。 只有就会过期。所以关注技术。 若关心资源，那就需要你们自己同时做下载。或者通过id再拿到一个新的地址。
