### ISSUE TITLE
求可选清晰度的版本

### ISSUE THREAD

**Issue by glimjoe** [xiyouMc/WebHubBot#18]
重新看了下代码，原来是从embed页面抓的下载地址，但是这里面抓的是480P的视频，所以能否来个720P的版本？不过720P的视频embed没法看，抓起来也比较麻烦，大佬有没有这个想法？

**Comment by xiyouMc** [comment]
@glimjoe 1080的都有。 不过得你们去分析下页面逻辑。 我这里不关注数据了。谢谢。

**Comment by blackmatch** [comment]
@glimjoe 我用node写了个默认下载最高清的版本[传送门](https://github.com/blackmatch/pornhub-downloader):sparkles:
