### ISSUE TITLE
OS 10.12.3

### ISSUE THREAD

**Issue by mumusa** [xiyouMc/WebHubBot#21]
iMac:PornHub iMac$ pip list
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
altgraph (0.10.2)
bdist-mpkg (0.5.0)
bonjour-py (0.3)
certifi (2017.4.17)
chardet (3.0.4)
cssselect (1.0.1)
idna (2.5)
lxml (3.8.0)
macholib (1.5.1)
matplotlib (1.3.1)
modulegraph (0.10.4)
numpy (1.8.0rc1)
parsel (1.2.0)
pip (9.0.1)
py2app (0.7.3)
pyasn1-modules (0.0.9)
PyDispatcher (2.0.5)
pymongo (3.4.0)
pyobjc-core (2.5.1)
pyobjc-framework-Accounts (2.5.1)
pyobjc-framework-AddressBook (2.5.1)
pyobjc-framework-AppleScriptKit (2.5.1)
pyobjc-framework-AppleScriptObjC (2.5.1)
pyobjc-framework-Automator (2.5.1)
pyobjc-framework-CFNetwork (2.5.1)
pyobjc-framework-Cocoa (2.5.1)
pyobjc-framework-Collaboration (2.5.1)
pyobjc-framework-CoreData (2.5.1)
pyobjc-framework-CoreLocation (2.5.1)
pyobjc-framework-CoreText (2.5.1)
pyobjc-framework-DictionaryServices (2.5.1)
pyobjc-framework-EventKit (2.5.1)
pyobjc-framework-ExceptionHandling (2.5.1)
pyobjc-framework-FSEvents (2.5.1)
pyobjc-framework-InputMethodKit (2.5.1)
pyobjc-framework-InstallerPlugins (2.5.1)
pyobjc-framework-InstantMessage (2.5.1)
pyobjc-framework-LatentSemanticMapping (2.5.1)
pyobjc-framework-LaunchServices (2.5.1)
pyobjc-framework-Message (2.5.1)
pyobjc-framework-OpenDirectory (2.5.1)
pyobjc-framework-PreferencePanes (2.5.1)
pyobjc-framework-PubSub (2.5.1)
pyobjc-framework-QTKit (2.5.1)
pyobjc-framework-Quartz (2.5.1)
pyobjc-framework-ScreenSaver (2.5.1)
pyobjc-framework-ScriptingBridge (2.5.1)
pyobjc-framework-SearchKit (2.5.1)
pyobjc-framework-ServiceManagement (2.5.1)
pyobjc-framework-Social (2.5.1)
pyobjc-framework-SyncServices (2.5.1)
pyobjc-framework-SystemConfiguration (2.5.1)
pyobjc-framework-WebKit (2.5.1)
pyOpenSSL (0.13.1)
pyparsing (2.0.1)
python-dateutil (1.5)
pytz (2013.7)
queuelib (1.4.2)
requests (2.18.1)
scipy (0.13.0b1)
Scrapy (1.4.0)
service-identity (17.0.0)
setuptools (18.5)
six (1.10.0)
Twisted (17.5.0)
urllib3 (1.21.1)
w3lib (1.17.0)
xattr (0.6.4)
zope.interface (4.1.1)

========Error
Traceback (most recent call last):
  File "quickstart.py", line 1, in <module>
    from scrapy import cmdline
  File "/Library/Python/2.7/site-packages/Scrapy-1.4.0-py2.7.egg/scrapy/__init__.py", line 27, in <module>
    from . import _monkeypatches
  File "/Library/Python/2.7/site-packages/Scrapy-1.4.0-py2.7.egg/scrapy/_monkeypatches.py", line 20, in <module>
    import twisted.persisted.styles  # NOQA
  File "/Library/Python/2.7/site-packages/Twisted-17.5.0-py2.7-macosx-10.12-intel.egg/twisted/__init__.py", line 23, in <module>
    from twisted._version import __version__ as version
  File "/Library/Python/2.7/site-packages/Twisted-17.5.0-py2.7-macosx-10.12-intel.egg/twisted/_version.py", line 8, in <module>
    from incremental import Version
ImportError: No module named incremental

**Comment by xiyouMc** [comment]
从错误日志上来看，是少了 incremental 这个组件。 
https://pypi.python.org/pypi/incremental/17.5.0
Incremental is a small library that versions your Python projects.

**Comment by mumusa** [comment]
之前是通过easy_install 安装的scrapy，后来用pip后自动安装了incremental module
顺便提一下，如果twisted 版本是最新的17.5.0的话会用以下的问题,
AttributeError: 'module' object has no attribute 'OP_NO_TLSv1_1'
===解决方案是
sudo pip install twisted==13.1.0
via: https://stackoverflow.com/questions/42731760/attributeerror-module-object-has-no-attribute-op-no-tlsv1-1
