### ISSUE TITLE
能否添加视频分类或标签？

### ISSUE THREAD

**Issue by maxhis** [xiyouMc/WebHubBot#24]
扒下来几万条数据，有点乱，要是能有分类就完美了。

**Comment by xiyouMc** [comment]
@maxhis 嗯 数据目前确实只是放到数据库的。 分类的话 就得增加字段 按照 PornHub 的标签。

**Comment by maxhis** [comment]
会考虑加上标签吗？

另外，发现视频地址`quality_480p`不能播放了，提示403.

**Comment by xiyouMc** [comment]
会考虑的

**Comment by hackxx** [comment]
应该 更灵活的！

**Comment by zzos** [comment]
怎么用啊?爬不出来东西，要翻墙吗？这些个py的不会用，不能做出php爬虫吗

**Comment by xiyouMc** [comment]
@zzos 装一个 Python 的环境。 再按照文档的说明一步步就可以搞起来了。 需要挂个墙 。 Python 比 PHP 轻量一点。

**Comment by fckwall** [comment]
@maxhis , 403是由于抓回的视频地址有时限。这个就是WebHubBot抓回的一个地址：https://de.phncdn.com/videos/201709/30/134995111/480P_600K_134995111.mp4?ttl=1507539223&ri=1228800&rs=1240&hash=aad821972fbb803ade8e9169d64b718b
你可以看到`ttl=1507539223`。估计链接的有效期只有1个小时，超过之后就403了。

你可以参考`parse_ph_key`和`parse_ph_info`两个函数(https://github.com/xiyouMc/WebHubBot/blob/master/PornHub/PornHub/spiders/pornHubSpider.py#L34)
每次需要浏览视频的时候，通过DB里的link_url，重新爬一次该网页，获取最新的视频地址

**Comment by xiyouMc** [comment]
@fckwall 赞。  你的 PR 也很不错。 其次，对代码也很了解。

多问一句，这不是你的大号吧。

**Comment by fckwall** [comment]
@xiyouMc , 哈哈 一眼就看穿了。谢谢你开源的好东西！没有你这么胸怀坦荡，专门开了个马甲来提交不可描述的事:)

**Comment by maxhis** [comment]
@fckwall 赞，回头我自己加个处理。

**Comment by maxhis** [comment]
@xiyouMc 题外话，你ID里的xiyou不会是学校名字吧？

**Comment by xiyouMc** [comment]
@maxhis 是的。 我的母校 西邮

**Comment by xiyouMc** [comment]
@fckwall 可以加个微信 mcx1469

**Comment by maxhis** [comment]
@xiyouMc 07级校友飘过~~~

**Comment by xiyouMc** [comment]
@maxhis Wow... 学长好

**Comment by ppoot** [comment]
请问 有没有 登入账号密码的api地址呀

**Comment by xiyouMc** [comment]
@ppoot 都能下载了 还要账号密码做什么

**Comment by ppoot** [comment]
因为有些私人影片需要登入后加好友才能看到
