### ISSUE TITLE
python 3.5.2 connect with mongodb, and mongodb has username and password

### ISSUE THREAD

**Issue by jxua** [xiyouMc/WebHubBot#26]
code and error just like bellow

![image](https://user-images.githubusercontent.com/22673941/28606983-557e047a-720c-11e7-9b5c-4ced7a103a3a.png)
![image](https://user-images.githubusercontent.com/22673941/28607004-692ba220-720c-11e7-880b-3b0830548e31.png)
![image](https://user-images.githubusercontent.com/22673941/28607011-74fdb64c-720c-11e7-9bcb-a884edb33b87.png)

**Comment by xiyouMc** [comment]
@jxua Can u login mongo in shell?   

or , U can db.CreateUser a newer user, and  auth this user.
