### ISSUE TITLE
PH信息的JSON: 是空的

### ISSUE THREAD

**Issue by Geselle-Joy** [xiyouMc/WebHubBot#34]
第一天的时候爬虫是可以正常运行的，但是视频好像过了一段时间就过期了。

然后第二天爬虫的时候，发现返回的JSON信息都是空的了，是不是我的IP被封了还是怎么了？

**Comment by xiyouMc** [comment]
1、链接半小时失效。 2、有可能是 ip 被封了，你可以试试用浏览器访问下 xxxhub.com
