### ISSUE TITLE
于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败

### ISSUE THREAD

**Issue by aaronwf** [xiyouMc/WebHubBot#48]
DEBUG Retrying <GET https://www.pornhub.com/robots.txt> (failed 1 times): TCP connection timed out: 10060: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
是被屏蔽了吗？设置上代理也不行？

**Comment by xiyouMc** [comment]
目测被屏蔽了
