### ISSUE TITLE
python3.6不行吗？

### ISSUE THREAD

**Issue by dengbaoling** [xiyouMc/WebHubBot#50]
error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": http://landinghub.visualstudio.com/visual-cpp-build-tools
![_20180612114345](https://user-images.githubusercontent.com/17171011/41269100-e9d7fc40-6e35-11e8-9a14-b5737ba5ab5f.png)

**Comment by xiyouMc** [comment]
没兼容过 3
