### ISSUE TITLE
请问这是怎么回事？keyword argument 'converter'

### ISSUE THREAD

**Issue by tea1111980** [xiyouMc/WebHubBot#55]
![image](https://user-images.githubusercontent.com/16295097/44625753-488e7a00-a943-11e8-9d3b-24542470c0e9.png)

你的所有组件我已经全部安装了，但是运行它还是出现这个错误。

我的系统版本：CentOS 7.5 
我的Python版本：Python 2.7.5

**Comment by xiyouMc** [comment]
twisted 的问题 吧。 建议卸载 重装试试

**Comment by tea1111980** [comment]
这些我都解决了，可是爬到的下载地址 怎么都成这样了？如下图：
![image](https://user-images.githubusercontent.com/16295097/44644151-a4b9d280-aa05-11e8-9cb2-59bc7ac4616a.png)

**Comment by tea1111980** [comment]
再问一下，你用的那个连接数据库的客户端叫什么名字？

**Comment by xiyouMc** [comment]
@tea1111980 MongoDB 呀

**Comment by tea1111980** [comment]
我问的是连接到 MongoDB 的客户端。你用的是什么客户端？

**Comment by leelovejava** [comment]
> 再问一下，你用的那个连接数据库的客户端叫什么名字？

robo

**Comment by tea1111980** [comment]
> > 再问一下，你用的那个连接数据库的客户端叫什么名字？
> 
> robo

好的，谢谢，我已经解决了。
